# FreeRadius Container Image

# Start from official FreeRadius image.
FROM freeradius/freeradius-server:3.2.0

### Debugging tools to be used during development
##RUN apt-get update && apt-get install -y --no-install-recommends \
##    iproute2 \
##    iputils-ping \
##    netcat-openbsd

EXPOSE 1812/udp 1813/udp
