@startuml
allow_mixing

node "gNMI Adapter\nServer" {
    class ConfDgNMIServicer {
        adapter
        ---
        serve()
        ..gNMI interface..
        Capabilities()
        Get()
        Set()
        Subscribe()
        ....
        get_adapter()
        connect_adapter()
        get_connected_adapter()
        disconnect_adapter()
    }

    node ConfD {
        database CDB
    }

    database DemoData

    abstract class GnmiServerAdapter {
        {abstract} capabilities()
        {abstract} get()
        {abstract} set()
        {abstract} get_subscription_handler()
        {abstract} get_inst()
    }

    class GnmiConfDApiServerAdapter {
            capabilities()
            get()
            set()
            get_subscription_handler()
            get_inst()
    }

    class GnmiDemoServerAdapter {
            capabilities()
            get()
            set()
            get_subscription_handler()
            get_inst()
    }

    class GnmiNetconfServerAdapter {
            capabilities()
            get()
            set()
            get_subscription_handler()
            get_inst()
    }

    abstract class SubscriptionHandler {
        {abstract} get_sample()
        {abstract) get_monitored_changes()
        {abstract} start_monitoring()
        {abstract} stop_monitoring()
        {abstract} add_path_for_monitoring()
        ---
        add_subscription_list()
        sample()
        changes()
        stop()
        read()
        poll()
    }

    class GnmiConfDApiServerAdapter.SubscriptionHandler {
    }

    class GnmiDemoServerAdapter.SubscriptionHandler {
    }

    SubscriptionHandler <-- GnmiConfDApiServerAdapter.SubscriptionHandler
    SubscriptionHandler <-- GnmiDemoServerAdapter.SubscriptionHandler
    GnmiServerAdapter <-le- GnmiDemoServerAdapter
    GnmiServerAdapter <-le- GnmiConfDApiServerAdapter
    GnmiServerAdapter <.up. GnmiNetconfServerAdapter
    ConfDgNMIServicer "1" *-- GnmiServerAdapter
    GnmiServerAdapter "1" *-- SubscriptionHandler

    GnmiConfDApiServerAdapter <..> ConfD
    GnmiConfDApiServerAdapter.SubscriptionHandler <..> ConfD

    GnmiDemoServerAdapter <..> DemoData
    GnmiDemoServerAdapter.SubscriptionHandler <..> DemoData

}

@enduml