@startuml

node gNMIClient <<gNMI Adapter>> [
Client
]


node gNMIServer <<<gNMI Adapter>> [
Server
]

skinparam node {
backgroundColor<<gNMI Adapter>> lightsteelblue
}

node ConfD {
    database CDB
}

node DataProvider <<ConfD Application>> [
Data Provider
]

node Netconf <<device>> [
<i>NETCONF</i>
]

cloud net1
cloud net2
cloud net3

gNMIClient <-ri-> net1
net1 <-ri-> gNMIServer
gNMIServer <-ri-> net2
gNMIServer <.do.> net3
gNMIClient <~ri~> gNMIServer:gRPC
DataProvider <~le~> gNMIServer:TCP
ConfD <~up~> DataProvider:DP API
gNMIServer <~~> ConfD:CDB API\nMAAPI
gNMIServer <~~> Netconf:NETCONF
net2 <-up-> ConfD
net2 <-ri-> DataProvider
net3 <.le.> Netconf

@enduml
